# 07_generate.R
#
# The finish line: orchestrates writing every EMLassemblyline .txt template
# to disk from app state, then runs the same make_eml() -> eml_validate() ->
# write_eml() sequence as skeleton.Rmd, ending in a properly named
# <metadata_id>_metadata.xml.
#
# Deliberately split into:
#   - build_generation_script(): pure function, returns the full R script
#     as a string (what Tab 7's "preview" modal already shows) - this is
#     the reproducible artifact the user can save and re-run independently
#     of the app.
#   - run_generation(): actually executes the equivalent steps directly
#     (not by eval-ing the script string) so the app can report real
#     success/failure and surface EML::eml_validate()'s specific errors
#     back to the user without needing to parse script output.
#
# Keeping these separate matters: eval-ing generated script text as a way
# to "run" the pipeline would make error handling and testing much harder.
# Instead, run_generation() calls the same underlying package functions
# with the same arguments the emitted script describes - the script is a
# human-readable record, not the execution path.

#' Assemble the full reproducible R script from every tab's state, in
#' skeleton.Rmd order. Pure function.
build_generation_script <- function(high_level_state, people_state, tables_state,
                                    fields_state, geo_state, taxonomy_state,
                                    working_folder_var = "working_folder") {
  paste(
    '# --- Generated by bReezEML ---',
    'library(NPSdataverse)',
    'library(tidyverse)',
    '',
    glue::glue('{working_folder_var} <- getwd()'),
    glue::glue('data_files <- c({paste(sprintf("\\"%s\\"", tables_state$metadata$file_name), collapse = ", ")})'),
    glue::glue('data_names <- c({paste(sprintf("\\"%s\\"", tables_state$metadata$table_name), collapse = ", ")})'),
    glue::glue('data_descriptions <- c({paste(sprintf("\\"%s\\"", tables_state$metadata$description), collapse = ", ")})'),
    'data_urls <- c(rep("temporary URL", length(data_files)))',
    '',
    emit_high_level_chunk(high_level_state, working_folder_var),
    emit_people_chunk(people_state, working_folder_var),
    emit_fields_chunk(fields_state, working_folder_var),
    emit_geo_chunk(geo_state, working_folder_var),
    emit_taxonomy_chunk(taxonomy_state, working_folder_var),
    '',
    'my_metadata <- EMLassemblyline::make_eml(',
    glue::glue('  path = {working_folder_var},'),
    '  dataset.title = package_title,',
    '  data.table = data_files,',
    '  data.table.name = data_names,',
    '  data.table.description = data_descriptions,',
    '  data.table.url = data_urls,',
    '  temporal.coverage = c(startdate, enddate),',
    '  maintenance.description = data_type,',
    '  package.id = metadata_id,',
    '  return.obj = TRUE,',
    '  write.file = FALSE',
    ')',
    '',
    'EML::eml_validate(my_metadata)',
    '',
    glue::glue('EML::write_eml(my_metadata, file.path({working_folder_var}, paste0(metadata_id, ".xml")))'),
    sep = "\n"
  )
}

#' Actually execute the pipeline: write every .txt template to
#' `working_folder`, call make_eml(), validate, and write the final .xml.
#' Returns a list describing the outcome rather than throwing, so the Shiny
#' layer can display a clean success/failure message.
#'
#' @param working_folder existing, writable directory path
#' @return list(success = logical, message = character,
#'              xml_path = character or NULL,
#'              validation_errors = character vector or NULL)
run_generation <- function(working_folder, high_level_state, people_state,
                           tables_state, fields_state, geo_state, taxonomy_state) {
  
  if (!dir.exists(working_folder)) {
    return(list(success = FALSE, message = paste0("Working folder does not exist: ", working_folder)))
  }
  
  # 1. copy uploaded data files into the working folder under their
  #    original names, since EMLassemblyline/make_eml() expect the data
  #    files to actually live at `path` alongside the .txt templates.
  file_copy_ok <- purrr::map_lgl(seq_len(nrow(tables_state$metadata)), function(i) {
    row <- tables_state$metadata[i, ]
    dest <- file.path(working_folder, row$file_name)
    tryCatch({
      file.copy(row$file_loc, dest, overwrite = TRUE)
    }, error = function(e) FALSE)
  })
  if (!all(file_copy_ok)) {
    return(list(success = FALSE, message = "Failed to copy one or more data files into the working folder."))
  }
  
  # 2. write core metadata templates + overwrite with captured content
  result <- tryCatch({
    EMLassemblyline::template_core_metadata(path = working_folder, license = "CC0")
    
    writeLines(high_level_state$abstract, file.path(working_folder, "abstract.txt"))
    writeLines(high_level_state$methods, file.path(working_folder, "methods.txt"))
    writeLines(high_level_state$additional_notes, file.path(working_folder, "additional_info.txt"))
    
    keywords_df <- tibble::tibble(
      keyword = high_level_state$keywords,
      keywordThesaurus = "NPS Data Package"
    )
    readr::write_tsv(keywords_df, file.path(working_folder, "keywords.txt"))
    
    # 3. personnel.txt
    to_personnel_rows <- function(df, role) {
      if (nrow(df) == 0) return(NULL)
      tibble::tibble(
        givenName = df$givenName,
        surName = df$surName,
        organizationName = df$organizationName,
        electronicMailAddress = df$email,
        userId = df$userId,
        role = if (!is.null(df$role)) df$role else role,
        projectTitle = "",
        fundingAgency = "",
        fundingNumber = ""
      )
    }
    personnel_df <- dplyr::bind_rows(
      to_personnel_rows(people_state$authors, "creator"),
      to_personnel_rows(people_state$contacts, "contact"),
      to_personnel_rows(people_state$contributors, NA_character_)
    )
    readr::write_tsv(personnel_df, file.path(working_folder, "personnel.txt"))
    
    # 4. attributes + catvars, per data table
    for (file_name in names(fields_state)) {
      tbl_state <- fields_state[[file_name]]
      readr::write_tsv(tbl_state$attributes,
                       file.path(working_folder, paste0("attributes_", file_name, ".txt")))
      if (nrow(tbl_state$catvars) > 0) {
        readr::write_tsv(tbl_state$catvars,
                         file.path(working_folder, paste0("catvars_", file_name, ".txt")))
      }
    }
    EMLassemblyline::template_table_attributes(path = working_folder, data.table = tables_state$metadata$file_name, write.file = FALSE)
    
    # 5. geographic coverage (optional)
    if (isTRUE(geo_state$enabled)) {
      EMLassemblyline::template_geographic_coverage(
        path = working_folder, data.path = working_folder,
        data.table = geo_state$table, lat.col = geo_state$lat_col,
        lon.col = geo_state$lon_col, site.col = geo_state$site_col,
        write.file = TRUE
      )
    }
    
    # 6. taxonomic coverage (optional)
    if (isTRUE(taxonomy_state$enabled)) {
      EMLassemblyline::template_taxonomic_coverage(
        path = working_folder, data.path = working_folder,
        taxa.table = purrr::map_chr(taxonomy_state$pairs, "table"),
        taxa.col = purrr::map_chr(taxonomy_state$pairs, "column"),
        taxa.authority = taxonomy_state$authorities,
        taxa.name.type = "scientific", write.file = TRUE
      )
    }
    
    list(ok = TRUE)
  }, error = function(e) {
    list(ok = FALSE, message = paste0("Failed while writing metadata templates: ", conditionMessage(e)))
  })
  
  if (!isTRUE(result$ok)) {
    return(list(success = FALSE, message = result$message))
  }
  
  # 7. make_eml()
  my_metadata <- tryCatch({
    EMLassemblyline::make_eml(
      path = working_folder,
      dataset.title = high_level_state$package_title,
      data.table = tables_state$metadata$file_name,
      data.table.name = tables_state$metadata$table_name,
      data.table.description = tables_state$metadata$description,
      data.table.url = rep("temporary URL", nrow(tables_state$metadata)),
      temporal.coverage = c(high_level_state$start_date, high_level_state$end_date),
      maintenance.description = high_level_state$data_status,
      package.id = high_level_state$metadata_id,
      return.obj = TRUE,
      write.file = FALSE
    )
  }, error = function(e) {
    e
  })
  
  if (inherits(my_metadata, "error") || inherits(my_metadata, "condition")) {
    return(list(success = FALSE, message = paste0("make_eml() failed: ", conditionMessage(my_metadata))))
  }
  
  # 8. validate
  validation <- tryCatch(EML::eml_validate(my_metadata), error = function(e) e)
  if (inherits(validation, "condition")) {
    return(list(success = FALSE, message = paste0("Validation failed to run: ", conditionMessage(validation))))
  }
  if (!isTRUE(validation)) {
    return(list(
      success = FALSE,
      message = "EML did not pass schema validation.",
      validation_errors = attr(validation, "errors")
    ))
  }
  
  # 9. write final .xml - always named <metadata_id>_metadata.xml per
  #    project convention, regardless of what the user typed for
  #    metadata_id (the "_metadata" suffix is appended here, not required
  #    from the user, to guarantee the naming convention is always met).
  xml_filename <- paste0(high_level_state$metadata_id, "_metadata.xml")
  xml_path <- file.path(working_folder, xml_filename)
  
  write_result <- tryCatch({
    EML::write_eml(my_metadata, xml_path)
    TRUE
  }, error = function(e) e)
  
  if (!isTRUE(write_result)) {
    return(list(success = FALSE, message = paste0("Failed to write .xml: ", conditionMessage(write_result))))
  }
  
  list(success = TRUE, message = paste0("Successfully wrote ", xml_filename), xml_path = xml_path)
}